Repository hashicorp/terraform-provider-kubernetes-alpha, pull requests merged in 2020-08, with the labels that each got.

#98 Clarify experiment implications
  README.md
Labels: size/XS

#99 Add docs as required by the Registry
  docs/index.md
  docs/resources/kubernetes_manifest.md
  provider/provider.go
  templates/index.md.tmpl
Labels: size/XL

#100 Add CHANGELOG
  CHANGELOG.md
Labels: size/XS

#101 Add changelog updating script
  scripts/changelog-links.sh
Labels: size/S

#104 Update README with registry changes (#58)
  README.md
  docs/index.md
Labels: size/XS

#103 Delete workflow to build on tag since publishing to registry (#58)
  .github/workflows/release_binaries.yaml
Labels: size/S
