Repository hashicorp/terraform-provider-kubernetes-alpha, pull requests merged in 2020-09, with the labels that each got.

#109 Fix broken links in README
  README.md
  docs/index.md
Labels: documentation, size/XS

#113 Fix login with username and password
  provider/server.go
Labels: size/XS

#92 Defer client initialization
  examples/cluster-with-resources/.skip_checks
  examples/cluster-with-resources/README.md
  examples/cluster-with-resources/cluster/test.tf
  examples/cluster-with-resources/main.tf
  examples/cluster-with-resources/manifests/test.tf
  provider/clients.go
  provider/resource_hcl.go
  provider/server.go
Labels: enhancement, size/XL
