Repository hashicorp/terraform-provider-kubernetes-alpha, pull requests merged in 2021-05, with the labels that each got.

#202 Upgrade terraform-plugin-go to v0.3.0
  go.mod
  go.sum
  morph/morph.go
  morph/morph_test.go
  morph/scaffold.go
  morph/scaffold_test.go
  openapi/foundry.go
  openapi/foundry_test.go
  payload/from_value.go
  payload/from_value_test.go
  payload/to_value.go
  payload/to_value_test.go
  provider/apply.go
  provider/configure.go
  provider/plan.go
  provider/provider.go
  provider/provider_config.go
  provider/read.go
  provider/resource.go
  provider/validate.go
  provider/waiter.go
  vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/diagnostic.go
  vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/dynamic_value.go
  vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/dynamic_value_json.go
  vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/dynamic_value_msgpack.go
  vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/fromproto/attribute_path.go
  vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/fromproto/schema.go
  vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/toproto/attribute_path.go
  vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/toproto/dynamic_value.go
  vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/resource.go
  vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/schema.go
  vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/state.go
  vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tftypes/attribute_path_error.go
  vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tftypes/list.go
  vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tftypes/map.go
  vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tftypes/object.go
  vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tftypes/primitive.go
  vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tftypes/set.go
  vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tftypes/tuple.go
  vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tftypes/type.go
  vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tftypes/value_msgpack.go
  vendor/github.com/hashicorp/terraform-plugin-go/tftypes/attribute_path.go
  vendor/github.com/hashicorp/terraform-plugin-go/tftypes/attribute_path_error.go
  vendor/github.com/hashicorp/terraform-plugin-go/tftypes/diff.go
  vendor/github.com/hashicorp/terraform-plugin-go/tftypes/doc.go
  vendor/github.com/hashicorp/terraform-plugin-go/tftypes/list.go
  vendor/github.com/hashicorp/terraform-plugin-go/tftypes/map.go
  vendor/github.com/hashicorp/terraform-plugin-go/tftypes/object.go
  vendor/github.com/hashicorp/terraform-plugin-go/tftypes/primitive.go
  vendor/github.com/hashicorp/terraform-plugin-go/tftypes/set.go
  vendor/github.com/hashicorp/terraform-plugin-go/tftypes/tuple.go
  vendor/github.com/hashicorp/terraform-plugin-go/tftypes/type.go
  vendor/github.com/hashicorp/terraform-plugin-go/tftypes/unknown_value.go
  vendor/github.com/hashicorp/terraform-plugin-go/tftypes/value.go
  vendor/github.com/hashicorp/terraform-plugin-go/tftypes/value_json.go
  vendor/github.com/hashicorp/terraform-plugin-go/tftypes/value_msgpack.go
  vendor/github.com/hashicorp/terraform-plugin-go/tftypes/walk.go
  vendor/modules.txt
Labels: size/XXL

#203 Add support for non-structured custom resources
  provider/apply.go
  provider/plan.go
  provider/read.go
  provider/resource.go
  test/acceptance/nonstructuredcustomresource_test.go
  test/acceptance/testdata/NonStructuredCustomResource/custom_resource.tf
  test/acceptance/testdata/NonStructuredCustomResource/variables.tf
  test/acceptance/testdata/NonStructuredCustomResourceDefinition/customresourcedefinition.tf
  test/acceptance/testdata/NonStructuredCustomResourceDefinition/variables.tf
  test/helper/kubernetes/kubernetes_helper.go
Labels: size/XL

#214 Fixes for empty lists, sets and maps and lists containing dynamicPseudoType
  morph/morph.go
  morph/morph_test.go
  payload/to_value.go
  payload/to_value_test.go
  test/acceptance/customresourcedefinition_test.go
  test/acceptance/testdata/CustomResourceDefinition/customresourcedefinition.tf
Labels: size/L
