Repository hashicorp/terraform-provider-kubernetes-alpha, pull requests merged in 2021-06, with the labels that each got.

#220 Fix typo in ApplyResourceChange
  provider/apply.go
Labels: size/XS

#219 Add more test coverage of basic resources
  test/acceptance/cronjob_test.go
  test/acceptance/daemonset_test.go
  test/acceptance/hpa_test.go
  test/acceptance/job_test.go
  test/acceptance/namespace_test.go
  test/acceptance/secret_test.go
  test/acceptance/statefulset_test.go
  test/acceptance/testdata/CronJob/cronjob.tf
  test/acceptance/testdata/CronJob/variables.tf
  test/acceptance/testdata/DaemonSet/daemonset.tf
  test/acceptance/testdata/DaemonSet/variables.tf
  test/acceptance/testdata/HPA/hpa.tf
  test/acceptance/testdata/HPA/hpa_modified.tf
  test/acceptance/testdata/HPA/variables.tf
  test/acceptance/testdata/Job/job.tf
  test/acceptance/testdata/Job/variables.tf
  test/acceptance/testdata/Namespace/namespace.tf
  test/acceptance/testdata/Namespace/namespace_modified.tf
  test/acceptance/testdata/Namespace/variables.tf
  test/acceptance/testdata/Secret/secret.tf
  test/acceptance/testdata/Secret/variables.tf
  test/acceptance/testdata/StatefulSet/statefulset.tf
  test/acceptance/testdata/StatefulSet/variables.tf
Labels: size/XL

#222 Migrate most GitHub HashiBot behaviors to GitHub Actions
  .github/labeler-issue-triage.yml
  .github/labeler-pull-request-triage.yml
  .github/workflows/issue-comment-created.yml
  .github/workflows/issue-opened.yml
  .github/workflows/lock.yml
  .github/workflows/pull-request.yml
  .hashibot.hcl
Labels: size/M

#225 Add TF 1.0.0 to test matrix
  .github/workflows/acceptance_tests.yaml
Labels: size/XS

#226 Migrate from GitHub HashiBot pull_request_size_labeler behavior to GitHub Actions
  .github/workflows/pull-request.yml
  .hashibot.hcl
Labels: size/S

#228 .github/workflows: Fix waiting-response label removal
  .github/workflows/issue-comment-created.yml
Labels: size/XS
